### ISSUE TITLE
s390x support

### ISSUE THREAD

**Issue by raulcabello** [k3s-io/k3s-root#41]
We are working on building k3s-root on s390x, since we need the binaries generated in k3s-root in order to build rke2 on s390x. Unfortunately, buildroot doesn't support static builds on s390x https://bugs.busybox.net/show_bug.cgi?id=14256 
Would it be possible to use shared libraries instead of static?

**Comment by brandond** [comment]
It's partially so that we're not dependent on distro binaries to be up-to-date, there were (and still are I believe) a couple distros that have iptables versions that work poorly with recent versions of Kubernetes.

K3s has also historically been advertised in talks from @ibuildthecloud as running on a minimal OS that contained nothing but /bin/sh, so we bring our own everything.

**Comment by raulcabello** [comment]
ok, thanks for the info!
